[versions]
agp = "8.13.2"
kotlin = "2.3.0"
xposed-api = "82"
ezxhelper = "3.1.1-rc1"
core = "1.17.0"
documentfile = "1.1.0"
recyclerview = "1.4.0"
swiperefreshlayout = "1.2.0"

[libraries]
xposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed-api" }
ezxhelper-android-utils = { module = "io.github.kyuubiran.ezxhelper:android-utils", version.ref = "ezxhelper" }
ezxhelper-xposed-api = { module = "io.github.kyuubiran.ezxhelper:xposed-api-82", version.ref = "ezxhelper" }
ezxhelper-core = { module = "io.github.kyuubiran.ezxhelper:core", version.ref = "ezxhelper" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }