name: Android CI (Push)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/push-android-ci.yml'
      - 'app/**'
      - 'gradle/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
    
jobs:
  build:
    environment: main_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Write key
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            {
              echo "" >> gradle.properties
              echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
              echo KEY_ALIAS='onHit'
              echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}'
              echo KEYSTORE_FILE='key.jks'
            } >> gradle.properties
            echo ${{ secrets.KEYSTORE }} | base64 -d > key.jks
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: onHit-debug
          path: app/build/outputs/apk/debug/*

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: onHit-release
          path: app/build/outputs/apk/release/*

      - name: Send To Telegram Group
        env:
            TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        run: |
            wget https://raw.githubusercontent.com/0penPublic/onHit/refs/heads/misc/telegram_on_hit_ci_bot.py
            python3 -m pip install python-telegram-bot==22.5
            python3 telegram_on_hit_ci_bot.py
